language: node_js
node_js:
- 12
script:
- make ci
deploy:
  provider: npm
  email: btimby@gmail.com
  api_key:
    secure: izhWUnEVFGqXrJmC3W5i+uq7FGPh8teMb6x4gerG7CobR/+Cd6IkbWIMkluiyx/8eaR1tI+SFzKClv2339DVn9UfmsTFVlB8Q/wPX/OHrVG0LU2GTRY9uJglmR1er2JSszyTgBwi4oe9jm+6mQWtndZBSK1HmJFqyrNwY2T/DEXv52bif0pXycTRjdGBaEfiG2uz1FXKeJ0xQUIpDSoeibi7jzk6JvhN5aKDzbCDjZ3kT4ht7jwpyEEtkPi7x9a4nm8dtpkLz7BN4HPFCHKeK0ZM6fdCFBjVkfJrt8ySxy2+1q8QzQEm++upSOHRqaXBj4VRhijIgvUy58LULXMbW0x9SPHlRuQ7OXN6VESA+o/yrZuXWhVo8pAcsTN6yz56yf40OhCbpgRGqPHXAKE5ZHAQzRYHV/miReBBfen+MW6H1oO5HEu58VYW/+r8IwzvEhk9sUh0A4AuXq3cyQZ6gvLlSww+Os0mcUxExaN2sxnRJ0Egj6kmyWn1ne3f5lOs28KMMVCf7uhvx5rdfjdsVYoGt2NqN9EhoGyF1SE3Q/RNhLFQILINDP5hSYRPTCnhLssSqNKAX0t3EZEavpG1dQ+ThJbSFhLeSAXBr4nHUJu5v+BGyqrR972xtelbDc34b5dPxIqBrCGacKP25NChrhMexO4gxyz8lNPM0TkYfL8=
  on:
    branch: master
